/** constants */

export enum Province {
    EASTERN_CAPE = "EASTERN_CAPE",
    WESTERN_CAPE = "WESTERN_CAPE",
    NORTHERN_CAPE = "NORTHERN_CAPE",
    NORTH_WEST = "NORTH_WEST",
    FREE_STATE = "FREE_STATE",
    KWAZULU_NATAL = "KWAZULU_NATAL",
    GAUTENG = "GAUTENG",
    MPUMALANGA = "MPUMALANGA",
    LIMPOPO = "LIMPOPO"
}
